### ISSUE TITLE
Source Error 2000; Music Failing to Play & Unable to Download Music

### ISSUE THREAD

**Issue by ThatOneUnoriginal** [OuterTune/OuterTune#464]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions) AND any logs I have attached are taken with the DEBUG version (NOT release).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

These are technically two different things but I assume the problem is the same so I thought I'd just report it once.
**Attempt to Download Music;**

1. Go to any song
2. Attempt to download the song
3. Watch as it stalls and does nothing

**Attempt to Listen to Non-Downloaded Songs Whilst Logged In;**

1. Log into your YouTube Music account in OuterTune
2. Find a song that you haven't downloaded (which also fails as described above) 
3. Attempt to play the song, you should notice it fail and skip to the next (which will fail as well)
4. For testing purposes you can log out of your YouTube Music account and repeat step 2 and 3

### Expected behavior

**Downloading Music;** The music should download onto the device and then become available to listen to online.

**Attempting to Listen to Non-Downloaded Songs Whilst Logged In;** Assuming a stable connection, the music should be available to listen to regardless of if being logged into my YouTube Music account in OuterTune.

### Actual behavior

**Downloading Music;** It stalls and does (seemingly) nothing.
**Attempting to Listen to Non-Downloaded Songs Whilst Logged In;** Shows "Source error (2000)" and attempts to play the next song... which also fails... which attempts to play the next song until it chooses to stop the loop of failure.

### Screenshots/Screen recordings

![Image](https://github.com/user-attachments/assets/829064ce-4e33-43c5-b6ff-43e84385d682)
Screenshot showing the Source Error (2000) notification at the bottom

### OuterTune version

0.7.7

### Device & Android version

Google Pixel 8 w/ Android Version 15

**Comment by tinhsoftware** [comment]
I have the same problem. 
If i clear data and open the app without login with google account, music play normally.
The problem happened if i logged into google account.

**Comment by bobsteva** [comment]
I am also experiencing this issue across multiple devices and can concur, logging out does allow the music to play for a few songs. Seems like an account update pushed to YouTube broke Outertune again. Very weird but almost expected in this cat and mouse game.

**Comment by Figim** [comment]
**Potoken is created in two ways. Potoken created with cookies is different. Potoken created without cookies cannot be used with cookies, Visitordata and DATASYNC ID are not required. It is like this: Visitordata+Potoken (when not logged in), Cookies+Potoken(when logged in). Cookies only work with web_remix and web_music client. For cookies, use music.youtube instead of youtube.com. Potoken is required by yt. You should keep the "android system webview" application updated.

**Comment by constantbsn** [comment]
Same issue

**Comment by megalith52** [comment]
Same issue

**Comment by 14142000** [comment]
Issue happens with both uploaded and streamed music making the app completely useless unless you have pre-downloaded songs. 

I warned this issue was added back in the last update but I was told I'd have to upload a logcat from the latest beta which I was unable to do without completely making my apps non-functional for personal use. The issue was less severe in the last update however as relogging in fixed it.

**Comment by nonnogatto** [comment]
Same issue, app works fine if i log out from my G account. Once logged back in same error. 


> The issue was less severe in the last update however as relogging in fixed it.

@14142000 what do you mean ?

**Comment by PleaseFixThisShit** [comment]
Same here, error seems to be fixed once I load a backup from around February but comes back once i try to use cellular data

![Image](https://github.com/user-attachments/assets/1706ae53-fedb-47f7-8596-2401d47e1c37)

**Comment by PleaseFixThisShit** [comment]
Error doesn't seem to be happening anymore? I can play on cellular data fine now, though it could be because of a proxy/URI?

**Comment by nonnogatto** [comment]
@PleaseFixThisShit are you playing the music logged ? To me works only if i log out

**Comment by Paulo4lvarez** [comment]
I have the same problem as well. Haven't tried re-logging in, but I *think* we could try deleting all cache, doing a clean install and see what happens. Maybe it has to do with the login method changing or something?

**Comment by TristanDelcourt** [comment]
Same issue here

**Comment by LawrenceYoung2625** [comment]
The bug I getting right now is the (Source Error 2000 ) and you cant download any of songs when I Login my google acc and to fix that I need to logout my google acc to use the app and download any of songs again  TwT

**Comment by PleaseFixThisShit** [comment]
Never mind the issue seems to be back

**Comment by gechoto** [comment]
There are two issues at play here:

1. The web clients fail because of https://github.com/TeamNewPipe/NewPipeExtractor/issues/1287
2. The IOS client fails when logged in because it sends `onBehalfOfUser` but this is invalid without login and needs to be removed (will be fixed by https://github.com/OuterTune/OuterTune/pull/466)

**Comment by Eddgutierrez93** [comment]
Same issue

**Comment by arledos99** [comment]
Do we know when the problem will be resolved?

**Comment by 14142000** [comment]
> Same issue, app works fine if i log out from my G account. Once logged back in same error.
> 
> > The issue was less severe in the last update however as relogging in fixed it.
> 
> [@14142000](https://github.com/14142000) what do you mean ?

You could still download, uploaded music and also stream it, and also you could just re-log in to get music hosted by YouTube music to play again.

**Comment by 14142000** [comment]
Just tried the dev version in actions, it plays streamed music while logged in but not uploaded music 

![Image](https://github.com/user-attachments/assets/90e7b210-b22d-4e12-9ac9-0c86ffd42472)

**Comment by mikooomich** [comment]
![sddefault.jpg](https://github.com/user-attachments/assets/1153d2d2-d212-4d31-87d2-71429274701c)

**Comment by 14142000** [comment]
> ![sddefault.jpg](https://github.com/user-attachments/assets/1153d2d2-d212-4d31-87d2-71429274701c)

We thank you for your service.

You would think it would be harder to keep the functionality of the streamed music and not the music that you own and upload. But no. YouTube is backwards.

**Comment by arledos99** [comment]
will there be a new version or is there something else? it's still not working for me.

**Comment by FurqanSarkar** [comment]
same happening with my device.

**Comment by megafilth** [comment]
> I have the same problem. If i clear data and open the app without login with google account, music play normally. The problem happened if i logged into google account.

Exactly, the problem is the login, that provoke what app crash, use the app without login, i try Of that way and works perfectly

**Comment by ThatOneUnoriginal** [comment]
The issue has already been marked as resolved, but I wanted to confirm that the latest debug APK appears to have fixed both problems. I can now listen to non-downloaded songs while logged in and download songs locally without any issues.

**Comment by nonnogatto** [comment]
@ThatOneUnoriginal do we know when to expect the next release with those fixes ?

**Comment by DD3Boh** [comment]
https://github.com/OuterTune/OuterTune/releases/tag/v0.7.8

New release with the fix is out now. Enjoy :)

**Comment by Eddgutierrez93** [comment]
> https://github.com/OuterTune/OuterTune/releases/tag/v0.7.8
> 
> New release with the fix is out now. Enjoy :)

I have the same problem with the new version. 

![Image](https://github.com/user-attachments/assets/205c5d04-aef0-41ce-a1fa-cbc93640dc0d)
![Image](https://github.com/user-attachments/assets/1416b0de-cdeb-499b-bb59-eb59e7cb329e)

**Comment by DD3Boh** [comment]
> 
> I have the same problem with the new version.
> 

The new version should fix the logged in playback, I tested that before and after and it worked fine for me, while earlier it was broken.
About private videos, that's another issue that has been already mentioned and needs a different fix.
@gechoto correct me if I'm wrong please.

**Comment by gechoto** [comment]
> New release with the fix is out now. Enjoy :)

> I have the same problem with the new version.

@DD3Boh @Eddgutierrez93 

Only one of two issues was fixed. The other one still remains.
See my comment:
https://github.com/OuterTune/OuterTune/issues/464#issuecomment-2751938867

The IOS client does not work for all users and can result in 403 errors.

The web clients are still broken.
We have to wait for https://github.com/TeamNewPipe/NewPipeExtractor/issues/1287 and update NewPipeExtractor once it is fixed there.

---

Edit:

> The new version should fix the logged in playback

Not in all cases. YT sometimes blocks the IOS client (I guess depending on the "quality" of your IP address. This is why for some it works while on wifi but does not work on mobile internet or with a VPN.)

**Comment by Eddgutierrez93** [comment]
> > I have the same problem with the new version.
> 
> The new version should fix the logged in playback, I tested that before and after and it worked fine for me, while earlier it was broken. About private videos, that's another issue that has been already mentioned and needs a different fix. [@gechoto](https://github.com/gechoto) correct me if I'm wrong please.

I have the both problems, not only with my music uploaded but also with the streaming music too

**Comment by DD3Boh** [comment]
> > New release with the fix is out now. Enjoy :)
> 
> > I have the same problem with the new version.
> 
> [@DD3Boh](https://github.com/DD3Boh) [@Eddgutierrez93](https://github.com/Eddgutierrez93)
> 
> Only one of two issues was fixed. The other one still remains. See my comment: [#464 (comment)](https://github.com/OuterTune/OuterTune/issues/464#issuecomment-2751938867)
> 
> The IOS client does not work for all users and can result in 403 errors.
> 
> The web clients are still broken. We have to wait for [TeamNewPipe/NewPipeExtractor#1287](https://github.com/TeamNewPipe/NewPipeExtractor/issues/1287) and update NewPipeExtractor once it is fixed there.
> 
> Edit:
> 
> > The new version should fix the logged in playback
> 
> Not in all cases. YT sometimes blocks the IOS client (I guess depending on the "quality" of your IP address. This is why for some it works while on wifi but does not work on mobile internet or with a VPN.)

Yeah, I understood that only one of the two issues was fixed, what I didn't know is that Google randomly rejects the iOS client as well, hence why I thought that this fix would just work for most people for the time being.

I guess we will have to wait

**Comment by mirsella** [comment]
playback is fixed, i cleared my app data etc, now logged in, but now the downloads doesn't work (infinite loading), is this known or could be related to this issue ? thanks

**Comment by YuzuMSX** [comment]
Still happening after used an Premium Account and a guest
It looks like some of the songs are cached the quality

**Comment by yotoprules** [comment]
I keep getting 403 errors on my end. Songs sometimes play fully, other times partially, other times not at all, always 403 error, sometimes album art disappears.

**Comment by DrekAnon** [comment]
![Image](https://github.com/user-attachments/assets/db317753-5e60-4f4d-af23-e7a6592ffcf4)
I'm getting error 2000, "sign in to confirm you're not a bot" when signed in on 0.7.8

**Comment by mizzledos** [comment]
Just here to say I'm still having this issue, exactly as described. I've tried uninstalling and reinstalling, logging in and out of YouTube account sync, and nothing has fixed it. Interestingly, I can now sometimes play an undownloaded song that I look up, but downloading doesn't work at all.
