### ISSUE TITLE
[ALL PLAYBACK ERRORS] Playback Error 403 / 2004 / Unknown error / Playback stops atfter 30 seconds / Sign in to confirm you're not a bot / This video is private / this video is inappropriate for some users

### ISSUE THREAD

**Issue by RichSexum** [OuterTune/OuterTune#468]
# Megathread for playback errors
- Playback Error 403
- Source error 2004
- Unknown error
- Playback stops atfter 30 seconds
- Sign in to confirm you're not a bot
- This video is private
- This video is inappropriate for some users

Other relevant discussion 
- #476 
- #523

### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions) AND any logs I have attached are taken with the DEBUG version (NOT release).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

step 1: play any song
step 2: when the songs up to 30 seconds or more the songs automatically jump to the next actually.
step 3: every song auto skip the songs between them.

### Expected behavior

![Image](https://github.com/user-attachments/assets/ddeeaf64-7737-44f6-8cc1-bab44485ca15)

### Actual behavior

this happened instead the songs reach 30 seconds or more!

### Screenshots/Screen recordings

![Image](https://github.com/user-attachments/assets/454a1a1d-4c07-4afb-807c-9508a894c8c3)

### OuterTune version

0.7.7

### Device & Android version

Poco x3 pro android 15 custom rom Evolution X

**Comment by gechoto** [comment]
This needs to be fixed in NewPipeExtractor: https://github.com/TeamNewPipe/NewPipeExtractor/issues/1287

**Comment by Figim** [comment]
It happens even when you're not logged in.

**Comment by amazfs** [comment]
the error is raised even if you move the cursor beyond 30sec (latest release)

**Comment by yotoprules** [comment]
Same problem on my end.

**Comment by teekamsuthar** [comment]
Same issue happening a lot of times

**Comment by teekamsuthar** [comment]
Any fixes?

**Comment by amazfs** [comment]
> Any fixes?

Disconnect and re connect to internet

**Comment by dantufis** [comment]
I have the same error on samsung galaxy s24 ultra and some oem car navigation . Problem is, sometimes this error comes from the start of the song not after 30 sec and jump to next song and so on.

**Comment by anxiouslelimo** [comment]
@gechoto Since the upstream is slow to merge the pull request in this case, is it feasible to create a newpipe extractor fork and incorporate in outertune? Something like this https://github.com/libre-tube/LibreTube/pull/7293

**Comment by gechoto** [comment]
> [@gechoto](https://github.com/gechoto) Since the upstream is slow to merge the pull request in this case, is it feasible to create a newpipe extractor fork and incorporate in outertune? Something like this [libre-tube/LibreTube#7293](https://github.com/libre-tube/LibreTube/pull/7293)

For OuterTune it would be easy to switch to a NewPipeExtractor fork temporarily but currently there is no fork which fully works.

we need someone to fix https://github.com/TeamNewPipe/NewPipeExtractor/issues/1289 first

**Comment by ZIKEE007** [comment]
https://github.com/user-attachments/assets/2643bbc4-7e5c-44e1-b6ed-d1d4168acc78


Please check also found the same bug everytime.

**Comment by ZIKEE007** [comment]
![Image](https://github.com/user-attachments/assets/cdfb7f42-6c83-46d8-95ea-d776b4194856)

![Image](https://github.com/user-attachments/assets/6109a10e-9462-42a9-a11a-e5aa194eeb9f)

Please check.Everytime when I use the app same bug or error found.

**Comment by ZIKEE007** [comment]
I also found the same error everytime. 
Logs (https://pastebin.com/9czGRTUB)

**Comment by Paulo4lvarez** [comment]
I also began having it. It came out of nowhere. Tried to reconnect to Internet and log out and back in to my account, but no luck so far. Luckily I have lots of songs downloaded.

**Comment by Gurinder1456** [comment]
I am have the same issue even in the latest update

**Comment by SheepCommander** [comment]
I checked the latest debug builds just in case but still having playback issues.

Weirdly the latest build of OuterTune works perfectly on my carrier (T Mobile LTE) but does not work on my Wi-Fi, while the latest build of InnerTune (by rcky844) is the opposite.

OuterTune works on my mobile data, InnerTune does not. InnerTune works on my wifi, OuterTune does not.

**Comment by hegehog8761** [comment]
I have a very similar issue however mine causes the app to only work with some songs, some songs will just load fine and others simply won't load at all, it doesn't affect downloaded songs for me, only new songs

**Comment by code913** [comment]
> OuterTune works on my mobile data, InnerTune does not. InnerTune works on my wifi, OuterTune does not.

For me InnerTune, Joss Music and OuterTune work on mobile data (Jio 4G) but only OuterTune works on wifi

**Comment by code913** [comment]
Welp all innertune forks stopped working on both wifi and data for me. Signing in doesn't remove the bot message

**Comment by SheepCommander** [comment]
Anyone tried Metrolist? It's been working for me

**Comment by yotoprules** [comment]
> Anyone tried Metrolist? It's been working for me

Metrolist is the only fork that works... except it's also the only one where the search doesn't work. Stopped working a few days ago for me at least. If I sign out it works though.

**Comment by SheepCommander** [comment]
For me Search doesn't work from Android Auto, but other than that basic things work perfectly.

**Comment by Bhuvan9407** [comment]
Metrolist is working perfectly especially the download feature

**Comment by n0aaz** [comment]
Happens for me on about every song on the latest build, V0.81. Makes it basically unusable sadly  
Also happens on 0.90 alpha 3. Really around the 30s mark every single time

Just tried Metrolist that doesn't have this issue. It's unclear to me how their implementation is different though

**Comment by RayneRPT** [comment]
Hey there, for me only works with WiFi, even on the last 9.0 version.. love the fact I can use it in Android Auto but unfortunately the 30s playback time issue is a no go. 
What I do is Listening from Brave Browser and no problem, but can't change tracks on AA.
Hope this gets fixed, been using the app and has a lot of potential.

**Comment by Vishcot** [comment]
Metrolist and opentune is working well as of now.

**Comment by Coinwillwin** [comment]
This is cool but I STILL DONT KNOW HOW TO FIX THE FACT THAT IT STOPS AFTER 30 SECONDS

**Comment by lynncarvalho** [comment]
Same Issue

**Comment by th3y** [comment]
Maybe a dumb question, but why not use NewPipeExtractor for StreamInfo.getInfo().audioStreams and get the metadata from the classic way?

**Comment by mikooomich** [comment]
> Maybe a dumb question, but why not use NewPipeExtractor for StreamInfo.getInfo().audioStreams and get the metadata from the classic way?

Any reasons why? I don't think that is the issue here, is it?

**Comment by th3y** [comment]
> > Maybe a dumb question, but why not use NewPipeExtractor for StreamInfo.getInfo().audioStreams and get the metadata from the classic way?
> 
> Any reasons why? I don't think that is the issue here, is it?

Because i have been testing this way and im not getting any playback issues (For now) (Of course i can't play age restricted videos).
Also, there's another open source project here that its using the logic from SmartTube to fix playback issues (And also playing age restricted videos)

**Comment by pixlxip** [comment]
I have gotten it working again (at least temporarily) by:

- Make a backup through the app
- Uninstall Outertune
- Install it again
- Restore the backup
- Clear cache and force quit through Android app settings

Not sure if this will work for everyone, but this worked for me so I thought I'd share.

**Comment by MetalDroid** [comment]
> Happens for me on about every song on the latest build, V0.81. Makes it basically unusable sadly Also happens on 0.90 alpha 3. Really around the 30s mark every single time
> 
> Just tried Metrolist that doesn't have this issue. It's unclear to me how their implementation is different though

Because it tries to use the ANDROID_VR client first, since the iOS client is the problematic one.

**Comment by claxcian** [comment]
Still this damned error even with the latest version 0.9. But hasn't it been fixed?

**Comment by zhengma021** [comment]
same here any updates?

**Comment by 0nini00** [comment]
我也是，为什么会出现这种情况呢

**Comment by ArtKa9** [comment]
Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.

**Comment by qwertiger** [comment]
> Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.

The strange thing here is, that I actually had it vice versa:
On wifi all worked as expected, but not on the data

**Comment by th3y** [comment]
> > Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.
> 
> The strange thing here is, that I actually had it vice versa: On wifi all worked as expected, but not on the data

It's IP Ban (But its temporal most of the times, depends on the ISP)

**Comment by qwertiger** [comment]
> > > Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.
> > 
> > 
> > The strange thing here is, that I actually had it vice versa: On wifi all worked as expected, but not on the data
> 
> It's IP Ban (But its temporal most of the times, depends on the ISP)

I think you might be right, but it never happened for me on Metrolist or SimpMusic (apps with the similar functionality)

**Comment by rubel-sh** [comment]
Facing same issue

**Comment by code913** [comment]
> > > Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.
> > 
> > 
> > The strange thing here is, that I actually had it vice versa: On wifi all worked as expected, but not on the data
> 
> It's IP Ban (But its temporal most of the times, depends on the ISP)

Shouldn't IP bans prevent you from using the official youtube/youtube music apps too? Never faced an issue with those

**Comment by RayneRPT** [comment]
It's not IP Ban, the official apps work just fine, also there is other apps similar to this one and it's working. I gave up using this one.

**Comment by sukoshiotokonoko** [comment]
> > Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.
> 
> The strange thing here is, that I actually had it vice versa:
> On wifi all worked as expected, but not on the data

Actually this has swapped randomly for me, someties both, sometimes neither, sometimes one or the other, and sometimes it would only work at different times or different places, or even different times at a different place. It is widely inconsistent.

**Comment by th3y** [comment]
> > > > Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.
> > > 
> > > 
> > > The strange thing here is, that I actually had it vice versa: On wifi all worked as expected, but not on the data
> > 
> > 
> > It's IP Ban (But its temporal most of the times, depends on the ISP)
> 
> I think you might be right, but it never happened for me on Metrolist or SimpMusic (apps with the similar functionality)

About metrolist, yes.
About SimpMusic, it's using functional potoken now (And i think its the only one using it currently), but its imported from another popular app (Can't say the name).
Metrolist is using newpipeextractor from libretube, but its not actually working, its using ios or avr for playback. (Same here)

**Comment by qwertiger** [comment]
> > > > > Hey everyone, I had the same issue. For me the only solution was just to switch from wifi to data transfer. I know it's not ideal but it works.
> > > > 
> > > > 
> > > > The strange thing here is, that I actually had it vice versa: On wifi all worked as expected, but not on the data
> > > 
> > > 
> > > It's IP Ban (But its temporal most of the times, depends on the ISP)
> > 
> > 
> > I think you might be right, but it never happened for me on Metrolist or SimpMusic (apps with the similar functionality)
> 
> About metrolist, yes. About SimpMusic, it's using functional potoken now (And i think its the only one using it currently), but its imported from another popular app (Can't say the name). Metrolist is using newpipeextractor from libretube, but its not actually working, its using ios or avr for playback. (Same here)

Interestingly, I never had the playback issues with Metrolist and its loading of the songs / caching / playback is actually the fastest among the others mentioned (at least for me)

**Comment by qwertiger** [comment]
> It's not IP Ban, the official apps work just fine, also there is other apps similar to this one and it's working. I gave up using this one.

Yes, for me this is the showstopper for this app as well

**Comment by G0razd** [comment]
It happened to me too, i fixed it by turning off "Use account for browsing content", i have the app localized so it might be worded differently, but i think its an account api ban, if youtube sences you are using new pipe or something, but thats just guess. TBO this isnt the first app i used so I guess it's a result of using a different one.

**Comment by qwertiger** [comment]
> It happened to me too, i fixed it by turning off "Use account for browsing content", i have the app localized so it might be worded differently, but i think its an account api ban, if youtube sences you are using new pipe or something, but thats just guess. TBO this isnt the first app i used so I guess it's a result of using a different one.

Thank you very much for this!
I did the same and it looks like now everything works correctly (on both wifi and data :)
This is the setting which needs to stay disabled:

![Image](https://github.com/user-attachments/assets/3ce1a634-f014-4033-8383-9579de756d33)


Not sure if this has also the effect on the playback, but now it looks like the songs are being loaded / cached / starts to play much faster!

**Comment by qwertiger** [comment]
Update:
I tried the method mentioned above, but unfortunately it doesn't help in the "long term". Issue came back after some listenings.
So the above method actually doesn't fix the problem!

**Comment by eddie-LA** [comment]
I'm getting "video not available" with some of my songs that work fine with the original client. It's quite jarring because my music just stops, it doesn't even skip the problematic songs. Clicking next manually doesn't resolve it either, I have to do play/pause on the next song to continue. 
Is it somehow related to this issue?

**Comment by MasterCraft6969** [comment]
Is there any fix to this yet?

**Comment by mikooomich** [comment]
Plz test 

https://github.com/OuterTune/OuterTune/actions/runs/16693816957

**Comment by Axhyy** [comment]
> Plz test
> 
> https://github.com/OuterTune/OuterTune/actions/runs/16693816957

This has fixed the issue for me, had an uninterrupted hour listening session.

**Comment by mudrhiod** [comment]
> Plz test
> 
> https://github.com/OuterTune/OuterTune/actions/runs/16693816957

The issue seems to be fixed for me also

**Comment by RayneRPT** [comment]
~It has fixed the streaming issue but now audio quality is low.
If you have another app you will notice the big difference between them. I would  prefer using OuterTune because it has more functionality with Android Auto where I use it the most.
Edit : it's fixed.~

Well playback error again. 😔

0.9.2 (64) | full
com.dd3boh.outertune | release
samsung pa3q (SM-S938B)
35 (AP3A.240905.015.A2)

OuterTune player error

X1.o: Source error
	at X1.P.t(SourceFile:17)
	at X1.P.handleMessage(SourceFile:453)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:342)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: T1.A: Response code: 403
	at V1.a.a(SourceFile:401)
	at T1.q.a(SourceFile:310)
	at T1.I.a(SourceFile:3)
	at U1.f.k(SourceFile:276)
	at U1.f.a(SourceFile:176)
	at U1.f.k(SourceFile:276)
	at U1.f.a(SourceFile:176)
	at T1.G.a(SourceFile:12)
	at T1.H.a(SourceFile:9)
	at g2.P.a(SourceFile:24)
	at j2.i.run(SourceFile:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
	at java.lang.Thread.run(Thread.java:1119)

**Comment by DanielProg39** [comment]
> 0.9.2 (64) | full
com.dd3boh.outertune | release

@RayneRPT It looks like you're using the latest release version of OuterTune, which doesn't yet include the relevant changes. Please try installing the debug build from [here](https://github.com/OuterTune/OuterTune/actions/runs/16693816957), which does incorporate these updates, and provide feedback on it.

If you have compiled the release build yourself using the latest changes, I apologise for the confusion.

**Comment by RayneRPT** [comment]
> > 0.9.2 (64) | full
> > com.dd3boh.outertune | release
> 
> [@RayneRPT](https://github.com/RayneRPT) It looks like you're using the latest release version of OuterTune, which doesn't yet include the relevant changes. Please try installing the debug build from [here](https://github.com/OuterTune/OuterTune/actions/runs/16693816957), which does incorporate these updates, and provide feedback on it.
> 
> If you have compiled the release build yourself using the latest changes, I apologise for the confusion.

You're right at first I used the debug version to test. I didn't checked if it was already implemented and installed the latest public release. Stupid me. 😑

Thank you, cheers.

**Comment by sam-reza** [comment]
> > 0.9.2 (64) | full
> > com.dd3boh.outertune | release
> 
> [@RayneRPT](https://github.com/RayneRPT) It looks like you're using the latest release version of OuterTune, which doesn't yet include the relevant changes. Please try installing the debug build from [here](https://github.com/OuterTune/OuterTune/actions/runs/16693816957), which does incorporate these updates, and provide feedback on it.
> 
> If you have compiled the release build yourself using the latest changes, I apologise for the confusion.

Is it possible this tag/msg?

![Image](https://github.com/user-attachments/assets/9c47f25d-134f-42ef-baad-aa6128a24038)

**Comment by Catniped** [comment]
still broken for me

```
0.10.0-b2 (68) | full
com.dd3boh.outertune | userdebug
google oriole (Pixel 6)
36 (BP2A.250605.031.A5)

OuterTune player error

androidx.media3.exoplayer.ExoPlaybackException: Source error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:934)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:906)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:309)
	at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
	at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
	at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
	at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
	at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
	at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
	at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110)
	at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:88)
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1109)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:453)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
	at java.lang.Thread.run(Thread.java:1119)
```

**Comment by NintendoTito** [comment]
I'm using the latest beta release and the playback error still persists. Is it necessary to install the debug version which has a build number before the beta release? 🤔

**Comment by RayneRPT** [comment]
And yes.. It has stopped working again, same issue, 30 sec and than error.

**Comment by TGC-TECH** [comment]
Playback Error 403 / 2004 is back again it seems.

**Comment by savageopress11** [comment]
Same issue for me, all media stops playing after 30 seconds with Source Error 2004/Error 403. I also get "Error 2000 this video is private" occasionally. I have tried logging out and re-logging in, clearing app cache, deleting and reinstalling app, changing networks and moble data, etc. 

I have tested similar apps such as OpenTune and have not received this error.

**Comment by NintendoTito** [comment]
> I have tested similar apps such as OpenTune and have not received this error.

I can confirm that OpenTune also works for me.

**Comment by Bipulai** [comment]
> # Megathread for playback errors
> * Playback Error 403
> * Source error 2004
> * Unknown error
> * Playback stops atfter 30 seconds
> * Sign in to confirm you're not a bot
> * This video is private
> * This video is inappropriate for some users
> 
> Other relevant discussion
> 
> * [PlaybackException: This video is private / this video is inappropriate for some users #476](https://github.com/OuterTune/OuterTune/issues/476)
> * [Error 2000: Sign in to confirm you're not a bot #523](https://github.com/OuterTune/OuterTune/issues/523)
> 
> ### Checklist
> * [x]  I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions) AND any logs I have attached are taken with the DEBUG version (NOT release).[x]  I've checked that there is no open or closed issue about this bug.[x]  This issue contains only one bug.[x]  The title of this issue accurately describes the bug.
> 
> ### Steps to reproduce the bug
> step 1: play any song step 2: when the songs up to 30 seconds or more the songs automatically jump to the next actually. step 3: every song auto skip the songs between them.
> 
> ### Expected behavior
> ![Image](https://github.com/user-attachments/assets/ddeeaf64-7737-44f6-8cc1-bab44485ca15)
> 
> ### Actual behavior
> this happened instead the songs reach 30 seconds or more!
> 
> ### Screenshots/Screen recordings
> ![Image](https://github.com/user-attachments/assets/454a1a1d-4c07-4afb-807c-9508a894c8c3)
> 
> ### Logs
> _No response_
> 
> ### OuterTune version
> 0.7.7
> 
> ### Device & Android version
> Poco x3 pro android 15 custom rom Evolution X
> 
> ### Additional information
> _No response_

I have already logged in and also using the latest  version but facing the same issue without skipping the song

**Comment by Bipulai** [comment]
> # Megathread for playback errors
> * Playback Error 403
> * Source error 2004
> * Unknown error
> * Playback stops atfter 30 seconds
> * Sign in to confirm you're not a bot
> * This video is private
> * This video is inappropriate for some users
> 
> Other relevant discussion
> 
> * [PlaybackException: This video is private / this video is inappropriate for some users #476](https://github.com/OuterTune/OuterTune/issues/476)
> * [Error 2000: Sign in to confirm you're not a bot #523](https://github.com/OuterTune/OuterTune/issues/523)
> 
> ### Checklist
> * [x]  I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions) AND any logs I have attached are taken with the DEBUG version (NOT release).[x]  I've checked that there is no open or closed issue about this bug.[x]  This issue contains only one bug.[x]  The title of this issue accurately describes the bug.
> 
> ### Steps to reproduce the bug
> step 1: play any song step 2: when the songs up to 30 seconds or more the songs automatically jump to the next actually. step 3: every song auto skip the songs between them.
> 
> ### Expected behavior
> ![Image](https://github.com/user-attachments/assets/ddeeaf64-7737-44f6-8cc1-bab44485ca15)
> 
> ### Actual behavior
> this happened instead the songs reach 30 seconds or more!
> 
> ### Screenshots/Screen recordings
> ![Image](https://github.com/user-attachments/assets/454a1a1d-4c07-4afb-807c-9508a894c8c3)
> 
> ### Logs
> _No response_
> 
> ### OuterTune version
> 0.7.7
> 
> ### Device & Android version
> Poco x3 pro android 15 custom rom Evolution X
> 
> ### Additional information
> _No response_

**Comment by Bipulai** [comment]
I'm also facing the issue providing I'm using latest version and also logged in

**Comment by sloaneyboo** [comment]
also also having this problem on the latest version

**Comment by DanielProg39** [comment]
YouTube has switched to a more advanced encryption system to block third-party apps from using login credentials. The best thing to do is to avoid logging in for now. You may need to wait some time after that for YT to work again. If your IP is blocked, use a VPN.

**Comment by pixlxip** [comment]
Interestingly, playback works for me on the debug build but not the release. I'm logged into both with the same account.
