### ISSUE TITLE
App crash / Unable to start app / IllegalArgumentException: cannot use a recycled source in createBitmap

### ISSUE THREAD

**Issue by mirsella** [OuterTune/OuterTune#724]
# *** NOTICE ***

> [!Note]
>
> This is a known issue with media3 1.8.0 and compatibility with certain ROMs/OEMs. Unfortunately, this crash is not something we can fix on an app level.
>
> This issue can be fixed by your device manufacturer. Please update your system.

### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/OuterTune/OuterTune/actions) AND any logs I have attached are taken with the DEBUG version (NOT release).
- [x] I've checked that there is no open or closed issue about this bug. [CHECK THE ISSUE TRACKER HERE](https://github.com/OuterTune/OuterTune/issues)
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.
- [ ] I've checked these boxes without reading carefully.

### Steps to reproduce the bug

- play any song
- close the app
- re open the app, try to play any song

### Expected behavior

- play

### Actual behavior

- it starts to play for like 100ms
- the app crash and close

### Logs

[outertune.log](https://github.com/user-attachments/files/21525637/outertune.log)

### OuterTune version

0.9.1 (63) |  core  DEBUG

### Device & Android version

poco f5, evolution x android 15

### Additional information

so on a fresh start of outertune it works (clearing the app data), but after restarting it it crash when trying to play a song.
if on a fresh start i load my backup, it crash directly, without having to restart the app.

**Comment by mikooomich** [comment]
This is a known issue with media3 1.8.0 and compatibility with certain ROMs/OEMs. Unfortunately, this crash is not something we can fix on an app level.

**Comment by mirsella** [comment]
thanks for the information!

there is no workaround ?

updating my ROM to android 16 beta will not help since the media3 version is in the application?

would you happen to recall what outertune version updated this package version? so I can use the previous one :)

thanks !

**Comment by mirsella** [comment]
if the media3 1.8.3 version was updated in outertune, do you know what version upgraded to it ? so I can revert to it :) thanks !

**Comment by mikooomich** [comment]
0.8.1 for sure wasn't using it. 0.9.x version I don't exactly remember

**Comment by mirsella** [comment]
yep i looked up the commit it was for 0.9, thanks

**Comment by mikooomich** [comment]
[OuterTune-0.9.3-b1-custommedia3-core-universal-release-65.apk.zip](https://github.com/user-attachments/files/21693236/OuterTune-0.9.3-b1-custommedia3-core-universal-release-65.apk.zip)
@PedrinSEP @mirsella  please try this build

**Comment by PedrinSEP** [comment]
@mikooomich This build works perfectly

**Comment by mirsella** [comment]
it works thanks a lot !

btw for the feedback, I tried using metrolist, but it doesn't cache everything as well as outertune and so is slower to navigate and start music :) happy to be back latest outertune

**Comment by mikooomich** [comment]
0.9.3

**Comment by mikooomich** [comment]
Issue is back...

**Comment by KweezyCode** [comment]
> Issue is back...

The problem hasn't gone away. 2-3 months ago, I tested it, and it was the same. Why not just remove the functionality that causes issues? The original Innertube works without problems; the issue is only with this fork.

**Comment by mirsella** [comment]
@KweezyCode as me and @PedrinSEP said, this was fixed, so it went away.

personally the problem is not even triggering now, im on latest github release and no crash.

**Comment by mikooomich** [comment]
It's very dependent on device manufacturer. Some people have no issues, some had it fixed in the latest releases as you said, some people have a broken gradient. some people still can't use the app at all...

The problem with downgrading Media3 is that it might fix this crash, but will certainly cause other issues (ex. playback resumption)

**Comment by Kibahor** [comment]
Hi,
So i encountered the same issue after messing with the app. At first i was thinking it was due to my big playlist of 2000 video that usually crash apps when trying to shuffle or enqueue but It happened also on random specific music or after nexting 3 music and even after reinstalling the app, it happened on random musics.
But after reading logs, it was for this reason and you telling me that wonderful application won't work because of my rom ?
I know often the problem resides between keyboard and chair, here the developer, but I'm bit confused.
What specifically made the jetpack media3 libraries won't work with my OS ?

Mi Note 10 Lite - RisingOS 6.3 (Android 15)

**Comment by Kibahor** [comment]
10-16 21:10:22.744 E/AndroidRuntime( 6473): FATAL EXCEPTION: MSLegacyStub:CompatSIT
10-16 21:10:22.744 E/AndroidRuntime( 6473): Process: com.dd3boh.outertune, PID: 6473
10-16 21:10:22.744 E/AndroidRuntime( 6473): java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:854)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:996)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at X2.b1.D(SourceFile:147)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at X2.Y0.run(SourceFile:25)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.os.Handler.handle
Callback(Handler.java:991)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.os.Looper.loopOnce(Looper.java:232)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.os.Looper.loop(Looper.java:317)
10-16 21:10:22.744 E/AndroidRuntime( 6473): 	at android.os.HandlerThread.run(HandlerThread.java:85)
