### ISSUE TITLE
Erro code 2004 403 issue accuring how long will you guys take to solve it

### ISSUE THREAD

**Issue by madvansh** [OuterTune/OuterTune#868]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/OuterTune/OuterTune/actions) AND any logs I have attached are taken with the DEBUG version (NOT release).
- [x] I've checked that there is no open or closed issue about this bug. [CHECK THE ISSUE TRACKER HERE](https://github.com/OuterTune/OuterTune/issues)
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.
- [x] I've checked these boxes without reading carefully.

### Steps to reproduce the bug

While playing any nusics it's show error 403 

### Expected behavior

While playing any nusics it's show error 403 

### Actual behavior

While playing any nusics it's show error 403 

### Screenshots/Screen recordings

While playing any nusics it's show error 403 

### Logs

While playing any nusics it's show error 403 

### OuterTune version

0.9.4

### Device & Android version

Android 15 

### Additional information

While playing any nusics it's show error 403  , I'm getting this error from the day before yesterday

**Comment by Feriman22** [comment]
Duplicated: https://github.com/OuterTune/OuterTune/issues/867

Also solved in v0.9.4.1, please update your app.

**Comment by madvansh** [comment]
> Duplicated: [#867](https://github.com/OuterTune/OuterTune/issues/867)
> 
> Also solved in v0.9.4.1, please update your app.

Bro bro yesterday I have updated this aap I also have 0.9.4 but the problem remain same

**Comment by Feriman22** [comment]
> > Duplicated: [#867](https://github.com/OuterTune/OuterTune/issues/867)
> > Also solved in v0.9.4.1, please update your app.
> 
> Bro bro yesterday I have updated this aap I also have 0.9.4 but the problem remain same

v0.9.4 and v0.9.4.1 are not the same.

**Comment by madvansh** [comment]
> > > Duplicated: [#867](https://github.com/OuterTune/OuterTune/issues/867)
> > > Also solved in v0.9.4.1, please update your app.
> > 
> > 
> > Bro bro yesterday I have updated this aap I also have 0.9.4 but the problem remain same
> 
> v0.9.4 d v0.9.4.1 are not the same.
Thanks brother I have updated the app you helped a lot

**Comment by LightslicerGP** [comment]
I'm on 0.9.4.1 and it still has the error
